export const detailData = {
  id: 3,
  created_at: '24-Dec-2019',
  updated_at: '',
  image_url: '',
  company: 'Century 21 BSD City',
  price: 'Rp 6.500.000.000',
  name: 'Nava Park BSD City',
  full_address: 'NavaPark Cluster Moonlight Blok 38D No. 55',
  is_commissionable: true,
  facilities: [
    {
      id: 1,
      iconId: 1,
      name: 'K. Tidur',
      desc: '3+1',
      measure_unit: '',
    },
    {
      id: 2,
      iconId: 2,
      name: 'K. Mandi',
      desc: '4',
      measure_unit: '',
    },
    {
      id: 3,
      iconId: 3,
      name: 'L. Tanah',
      desc: '275',
      measure_unit: 'M2',
    },
    {
      id: 4,
      iconId: 3,
      name: 'L. Bangunan',
      desc: '275',
      measure_unit: 'M2',
    },
    {
      id: 5,
      iconId: 3,
      name: '(P X L) Bangunan',
      desc: '25 x 100',
      measure_unit: 'M',
    },
    {
      id: 6,
      iconId: 3,
      name: '(P X L) Tanah',
      desc: '25 x 100',
      measure_unit: 'M',
    },
    {
      id: 7,
      iconId: 7,
      name: 'Jumlah Lantai',
      desc: '2',
      measure_unit: 'M',
    },
    {
      id: 8,
      iconId: 6,
      name: 'Listrik',
      desc: '3.000',
      measure_unit: 'W',
    },
    {
      id: 9,
      iconId: 5,
      name: 'Kapasitas Garasi',
      desc: '2',
      measure_unit: '',
    },
    {
      id: 10,
      iconId: 4,
      name: 'Kapasitas Parkir',
      desc: '2',
      measure_unit: '',
    },
    {
      id: 11,
      iconId: 99,
      name: 'Line Telepon',
      desc: '2',
      measure_unit: '',
    },
  ],
};
