export const listingData = [
  {
    id: 1,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '9000000000',
    name: 'Nava Park BSD City',
    full_address: 'asdlkfmasdklfm',
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    is_private: true,
    sale_status: 1, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 1,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
  {
    id: 2,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '6000000',
    name: 'Nava Park BSD City',
    full_address: '',
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    is_private: true,
    sale_status: 2, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 2,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
  {
    id: 3,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '8000000',
    name: 'Nava Park BSD City',
    full_address: '',
    is_private: false,
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    sale_status: 1, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 1,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
];

export const favData = [
  {
    id: 1,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '9000000000',
    name: 'Nava Park BSD City',
    full_address: 'asdlkfmasdklfm',
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    is_private: true,
    sale_status: 1, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 1,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
  {
    id: 2,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '6000000',
    name: 'Nava Park BSD City',
    full_address: '',
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    is_private: true,
    sale_status: 2, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 2,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
  {
    id: 3,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '8000000',
    name: 'Nava Park BSD City',
    full_address: '',
    is_private: false,
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    sale_status: 1, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 1,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
];

export const archiveData = [
  {
    id: 1,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '9000000000',
    name: 'Nava Park BSD City',
    full_address: 'asdlkfmasdklfm',
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    is_private: true,
    sale_status: 1, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 1,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
  {
    id: 2,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '6000000',
    name: 'Nava Park BSD City',
    full_address: '',
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    is_private: true,
    sale_status: 2, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 2,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
  {
    id: 3,
    created_at: '',
    updated_at: '',
    owner: 'Henry Scott',
    image_url: '',
    company: 'Century 21 BSD City',
    price: '8000000',
    name: 'Nava Park BSD City',
    full_address: '',
    is_private: false,
    address: 'Jl. Edutown Kav III.1, BSD, Tangerang Selatan',
    sale_status: 1, // 1 sale, 2 rent
    is_sold: true,
    propertyType: 1,
    is_commissionable: true,
    highlight_facilities: [
      {
        id: 1,
        name: 'K. Tidur',
        desc: '3+1',
        measure_unit: '',
      },
      {
        id: 2,
        name: 'K. Mandi',
        desc: '4',
        measure_unit: '',
      },
      {
        id: 3,
        name: 'L. Tanah',
        desc: '275',
        measure_unit: 'M',
      },
    ],
  },
];
